api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

app_name = "api"

router = routers.DefaultRouter()
router.register(r'posts', views.PostViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('add_post/', views.add_post),
    path('all_posts/', views.get_all_posts),
    path('post_details/<int:id>', views.post_details),
    path('dj_front/', views.dj_front_home, name='posts'),
    path('dj_front/<int:id>', views.dj_front_detail, name='post_detail')
]

theproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    userId = models.IntegerField()
    id = models.IntegerField(primary_key=True)
    title = models.TextField()
    body = models.TextField()

    def __str__(self):
        return self.title

    def snippetPost(self):
        return self.body[:50] + " ..."

api/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.models import User, Group
from rest_framework import viewsets, status
from rest_framework import permissions
from api.serializers import UserSerializer, GroupSerializer, PostSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Post
import requests

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]


class PostViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticated]

@api_view(['POST'])
def add_post(request):
    serializer = PostSerializer(data=request.data)
    if serializer.is_valid():
        checking_user = requests.get('https://jsonplaceholder.typicode.com/users').json()
        for user in checking_user:
            if serializer.validated_data.get('userId') == user['id']:
                print("User exists, ready to go.. ")
                serializer.save()
                return Response({"Status": "Post added"}, status=status.HTTP_201_CREATED)
            else:
                return Response({"Status": "User not found"}, status=status.HTTP_401_UNAUTHORIZED)

    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['Get'])
def get_all_posts(request):
    q = Post.objects.all()
    serializer = PostSerializer(q, many=True)
    # pemission_classes = [permissions.IsAuthenticated]
    return Response(serializer.data)


@api_view(['Get', 'PUT', 'DELETE'])
def post_details(request, id):

    try:
        post = Post.objects.get(pk=id)
        try_with_filter = Post.objects.filter(pk=id)
    except Post.DoesNotExist:
        try_with_filter = Post.objects.filter(pk=id)
        if try_with_filter:
            print("exitst")
        else:
            try:
                checking = requests.get('https://jsonplaceholder.typicode.com/posts').json()
                print("Cheking...")

                for dt in checking:
                    if dt['id'] == id:
                        print("Post exist online - add it to your db")

                        foundId = dt['id']
                        foundUserId = dt['userId']
                        foundTitle = dt['title']
                        foundBody = dt['body']

                        foundData = Post(id=foundId, userId=foundUserId, title=foundTitle, body=foundBody)

                        save_d = foundData.save()
                        if save_d:
                            return Response(status=status.HTTP_202_ACCEPTED)
                        else:
                            return Response(status=status.HTTP_400_BAD_REQUEST)

            except:
                print("Post not exist")

        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = PostSerializer(post)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = PostSerializer(post, data=request.data)
        if serializer.is_valid():
            title = serializer.validated_data['title']
            body = serializer.validated_data['body']
            serializer.save(title=title, body=body)
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        post.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


# Use templates to display
def dj_front_home(request):
    dj_posts = Post.objects.all().order_by('id')
    context = {
        'dj_posts': dj_posts
    }
    return render(request, 'posts.html', context)


def dj_front_detail(request, id):
    dj_post = Post.objects.get(id=id)

    context = {
        'dj_post': dj_post
    }

    return render(request, 'post_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block siteTitle %} {% endblock %}</title>
  </head>
  <body>

  {% block firstSection %} {% endblock %}


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block siteTitle %} Post {{dj_post.id}} {% endblock %}

{% block firstSection %}
    <div class="container-fluid">

        <h4 class="group inner list-group-item-heading">{{dj_post.title}}</h4>
        <p class="group inner list-group-item-text">{{dj_post.body}}</p>

    </div>
{% endblock %}

templates/posts.html
{% extends 'base.html' %}
{% load static %}

{% block siteTitle %} All posts {% endblock %}

{% block firstSection %}
<div class="container-fluid">
    <div class="row px-2">

        {% for djpost in dj_posts %}

        <div class="col-xs-12 col-lg-4 col-md-6 mt-4 mb-4 card">
            <h4 class="group inner list-group-item-heading">{{djpost.title}}</h4>
            <p class="group inner list-group-item-text">{{djpost.body}}</p>
            <div class="row">
              <div class="col-xs-12 col-md-6">
                <a class="btn btn-success" href="{% url 'api:post_detail' id=djpost.id %}">
                  Details
                </a>
              </div>
            </div>
          </div>

    {% endfor %}

    </div>
</div>
{% endblock %}